site:
  build: .
  ports :
   - "80:80"
  volumes:
   - /home/denisvieira/AndroidStudioProjects/android-practices/Book-Dominando-Android-2-Edicao-Nelson-Glauber/Cap-14-APIs-do-Google/Google-Cloud-Messaging/gcm-server/hotel_service:/var/www/html/
  links:
   - database
phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "8080:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=password
   links:
    - database:mysql
database:
  image: mysql:5.5
  ports:
   - "3306:3306"
  environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=tc_cars
     - MYSQL_USER=app
     - MYSQL_PASSWORD=password
